name: CHARM

volumes:
  vol-charm-flask-uploads:
    driver: local
  vol-charm-db:
    driver: local

networks:
  charm-public-net:
    driver: bridge

services:
  charm-nextjs:
    container_name: charm-nextjs
    restart: always
    build:
      context: ./
      dockerfile: charm-next.Dockerfile
    env_file:
      - ./.env
    ports:
      - "${WEB_PORT}:3000"
    networks:
      - charm-public-net

  charm-flask:
    container_name: charm-flask
    restart: always
    build:
      context: ./
      dockerfile: charm-flask.Dockerfile
    volumes:
      - vol-charm-flask-uploads:/services/charm-flask/uploads
    ports:
      - "${FLASK_PORT}:5000"
    networks:
      - charm-public-net
  charm-db:
    container_name: charm-db
    restart: always
    image: postgres:latest
    volumes:
      - vol-charm-db:/var/lib/postgresql/data
    env_file:
      - ./charm-db.env
    ports:
      - "${DB_PORT}:5432"
    networks:
      - charm-public-net
